# Generated by Django 3.0.2 on 2020-01-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pos_x',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='pos_y',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
