# Generated by Django 3.0.2 on 2020-01-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200107_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pos_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='pos_y',
            new_name='y',
        ),
    ]
