# Generated by Django 3.0.2 on 2020-01-10 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200107_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.CharField(default='No items in inventory', max_length=500),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT NAME', max_length=50)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adventure.Room')),
            ],
        ),
    ]
