# Generated by Django 3.0.2 on 2020-01-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_room_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
    ]
