# Generated by Django 3.0.2 on 2020-01-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_remove_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='DEFAULT DESCRIPTION', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, default='DEFAULT NAME', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='items',
            field=models.CharField(blank=True, default='DEFAULT ITEM', max_length=500, null=True),
        ),
    ]
